services:
  database:
    image: postgres:18.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=social
      - POSTGRES_PASSWORD=W9oqWPKZpZJ8cISlvvl9EeLwwSj5
      - POSTGRES_DB=social
    ports:
      - '5432:5432'
    networks:
      - social-net
    volumes:
      # ./postgres-data would live on the project
      # postgres-data lives in docker storage-area 
      # `$ docker volume ls` 
      # `$ docker volume inspect greenlight_postgres-data`
      - social-pg-data:/var/lib/postgresql/data 
  redis:
    image: redis:8.6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 30s
      timeout: 1m30s
      retries: 3
      start_period: 30s
    networks:
      - social-net
    volumes:
      - social-redis-data:/data
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   restart: unless-stopped
  #   environment:
  #       - REDIS_HOSTS=local:redis:6379
  #   ports:
  #       - "8081:8081"
  #   depends_on:
  #       - redis
  redis-insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_INSIGHT_HOST=0.0.0.0
      - REDIS_INSIGHT_ACCEPT_LICENSE=true # Accept EULA 
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - social-net
    volumes:
      - social-redisinsight-data:/data
networks:
  social-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8:1::/64
volumes:
    social-pg-data:
    social-redis-data:
    social-redisinsight-data: