name: deploy
on:
  push:
    tags:
      - 'v*' # Trigger only on version tags
permissions:
  id-token: 'write' # Required for WIF
  contents: 'read'

jobs:
  deploy:
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/checkout@v6
    # 1. Authenticate to GCP
    - id: Auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    # 2 Setup GCLOUD & Docker
    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@v3
    - name: Authorize Docker
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev
    # 3. Build app & Inject version
    - name: Build and push
      run: |
        VERSION=${GITHUB_REF_NAME}
        IMAGE="europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/api:${VERSION}"
        docker build \
          --build-arg VERSION=${VERSION} \
          -t $IMAGE .
        docker push $IMAGE
    # 4. Run Migrations (Using a Cloud Run Job)
      # This ensures the DB is ready BEFORE the new API starts
    # - name: Run Migrations
    #   run: |
    #     gcloud run jobs execute social-migration-job \
    #       --region us-central1 \
    #       --wait
    # 4. Deploy
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v3
      with:
        service: social-api
        image: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/api:${{ github.ref_name }}
        region: europe-west1
