name: release
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-24.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple